Add checkup tear-down capability
orelmisan/k8s-checkup-framework pull request #15
Opened 2022-03-08 14:29 UTC by orelmisan

This adds the capability to remove the checkup's Namespace.

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-03-08 15:20 UTC, ormergi requested changes

2022-03-08 16:07 UTC, orelmisan commented on pkg/checkup/workspace.go
> +	if err := w.deleteNamespace(client); err != nil {
IMO this can be postponed to the production version.

2022-03-08 16:11 UTC, orelmisan commented on cmd/checkup-launcher.go
> +		log.Fatalf("Failed to tear-down the checkup's environment: %v", err)
Done

2022-03-08 16:13 UTC, orelmisan commented
[Change:](https://github.com/orelmisan/k8s-checkup-framework/compare/b905005b03361e50093fa27e6809ae3cc279473f..7061fd7888843f517f12f825fc439abfb715b877)
Moved the call to workspace.Teardown() to an anonymous defered function so tear-down could take place if error occurs when executing or waiting for the checkup Job to finish.

2022-03-09 09:05 UTC, orelmisan commented on pkg/checkup/workspace.go
> +	name := w.namespace.Name
Done

2022-03-09 09:06 UTC, orelmisan commented on cmd/checkup-launcher.go
> +	defer func() {
This insures the Teardown method will be called in case of an error.

2022-03-09 10:47 UTC, orelmisan commented
[Change:](https://github.com/orelmisan/k8s-checkup-framework/compare/49ef7eee92538b7e143dd640ec5b27fc0b784e5c..c0bfdd93ac1232f4a63c7a54fbe2b92d1c01b5fb) Moved the defer code under the setup call.

2022-03-09 10:59 UTC, orelmisan commented
[Change:](https://github.com/orelmisan/k8s-checkup-framework/compare/c0bfdd93ac1232f4a63c7a54fbe2b92d1c01b5fb..86f7a894b986cd7d561d2bdd10cb6f584e2c0392) Changed the log printing in the defered function to log.Printf

2022-03-09 11:08 UTC, ormergi approved these changes
Thanks

2022-03-09 11:09 UTC, merged